<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'If a MAC address is entered a Wake-on-LAN packet will be sent to it whenever someone logs in' => 'Si une adresse MAC est renseignée un paquet magique (WOL) sera envoyé à chaque fois que quelqu\'un se connecte.',
  'If you don\'t know what this, leave it empty. Otherwise enter the subnet mask, e.g. 255.255.0.0' => 'Si vous ne connaissez pas cette fonctionnalité, laissez ce champ vide. Dans le cas contraire, saisissez le masque sous-réseau, comme par exemple : 255.255.0.0.',
  'Invalid MAC address' => 'L\'adresse MAC est incorrecte',
  'Invalid subnet mask' => 'Le masque sous-réseau est incorrect',
  'MAC address' => 'Adresse MAC',
  'Subnet mask' => 'Masque sous-réseau',
  'The current backend is not connectable at the moment' => 'La source actuelle n\'est pas connectable pour le moment',
  'The following items are only required if you want the backend to me woken using Wake on LAN' => 'Les options suivantes ne sont utiles que si vous souhaitez que la source soit réveillée par la fonction de réveil à distance (Wake-On-Lan).',
  'Unable to send WOL packet' => 'Impossibilité d\'envoyer un paquet magique (WOL)',
  'Waiting for connection' => 'En attente de connection',
  'Wake on LAN packet sent, this page will be automatically refreshed once the backend is reachable' => 'Le paquet magique (WOL) a été envoyé, cette page s\'actualisera dès lors que la source sera accessible.',
  'Backend created successfully' => 'Source créée avec succès',
  'Backend name' => 'Nom de la source',
  'Backend updated successfully' => 'Source mise à jour avec succès',
  'Changed backend to {backendName}' => 'Changement de source par : {backendName}',
  'Create new backend' => 'Créer une nouvelle source',
  'Default' => 'Défaut',
  'Hostname' => 'Nom de domaine',
  'Invalid credentials' => 'Identification invalide',
  'Manage backends' => 'Gérer les sources',
  'Password' => 'Mot de passe',
  'Port' => 'Port',
  'Proxy location' => 'Proxy',
  'See {readmeUrl} for how to configure this' => 'Voir ce lien : {readmeUrl} pour configurer ceci',
  'Set as default' => 'Par défaut',
  'The server does not ask for authentication' => 'Le serveur ne demande pas pour l\'authentification',
  'There must be a default backend' => 'Il doit y avoir une source par défaut',
  'This is where you configure your backends. A 
	backend is an instance of XBMC that the application connects to and serves 
	library contents from. If you specify more than one backend, a new item 
	will appear in the main menu, allowing you to easily switch backends.' => 'Ici vous configurez vos sources. Une source est une instance du logiciel XBMC qui gère le contenu de la librairie. Si vous configurez plusieurs sources, un nouvel objet apparaitra dans le menu, vous permettant de passer d\'une source à l\'autre.',
  'Unable to connect to {hostname}:{port}, make sure XBMC is running and has its web server enabled' => 'Impossible de se connecter à : {hostname}:{port}, assurez-vous que le logiciel XBMC est lancé avec son option Serveur Web activée',
  'Update {backendName}' => 'Mise à jour de : {backendName}',
  'Username' => 'Nom d\'utilisateur',
  'You can\'t delete the current backend. Please switch to another one if you want to delete this.' => 'Vous ne pouvez pas supprimer la source actuelle. Veuillez échanger avec une autre si vous souhaitez supprimer celle-ci',
  'You must configure a backend before you can use the application' => 'Vous devez configurer une source avant de pouvoir utiliser l\'application',
);
