<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'If the backend allows TCP connections from other machines, XBMC Video Server will use it to determine when triggered library updates are finished' => 'Si le serveur de hébergeant la source autorise des connexions TCP depuis d’autres ordinateurs, Kodi va utiliser ce type de connexion pour déterminer quand est-ce que les mises à jour de la vidéothèque déclenchées seront terminées.',
  'Library update triggered, this page will be automatically refreshed once the update has completed' => 'La mise à jour de la vidéothèque a été déclenchée, cette page sera actualisée automatiquement une fois que la mise à jour sera terminée.',
  'TCP port' => 'Port TCP',
  'The following item must only be changed if you\'ve changed the port through advancedsettings.xml' => 'L’option suivante doit être modifiée uniquement si le port par défaut a été modifié dans le fichier : advancedSettings.xml.',
  'Waiting for library update' => 'En attente… la vidéothèque est en cours de mise à jour.',
  'WebSocket connection not available, library updates will be performed synchronously' => 'Connexion WebSocket non disponible, les mises à jour de la vidéothèque seront effectuées de manière synchrone.',
  'You can leave this page at any time, the library update will finish in the background' => 'Cette page peut être fermée à tout moment, la mise à jour de la vidéothèque se terminera en arrière-plan.',
  'Backend created successfully' => 'La source a été créée avec succès.',
  'Backend name' => 'Nom de la source',
  'Backend updated successfully' => 'La source a été mise à jour avec succès.',
  'Changed backend to {backendName}' => 'Changement de source par : {backendName}',
  'Create new backend' => 'Créer une nouvelle source',
  'Default' => 'Défaut',
  'Hostname' => 'Nom de domaine',
  'If a MAC address is entered a Wake-on-LAN packet will be sent to it whenever someone logs in' => 'Si une adresse MAC est renseignée un paquet magique (WOL) sera envoyé à chaque fois que quelqu’un se connecte.',
  'If the backend has been powered off completely you\'ll have to turn it on manually.' => 'Si la source est complètement éteinte (signifiant que la carte réseau ne peut recevoir le paquet magique) celle-ci doit être démarrée manuellement.',
  'If you don\'t know what this, leave it empty. Otherwise enter the subnet mask, e.g. 255.255.0.0' => 'Si cette fonctionnalité vous est inconnue, merci de laisser ce champ vide. Dans le cas contraire, saisir le masque sous-réseau, comme par exemple : 255.255.0.0.',
  'Invalid MAC address' => 'L’adresse MAC est incorrecte',
  'Invalid credentials' => 'Identification invalide',
  'Invalid subnet mask' => 'Le masque sous-réseau est incorrect.',
  'MAC address' => 'Adresse MAC',
  'Manage backends' => 'Gérer les sources',
  'Password' => 'Mot de passe',
  'Port' => 'Port',
  'Proxy location' => 'Proxy',
  'See {readmeUrl} for how to configure this' => 'Voir ce lien : {readmeUrl} pour configurer ceci.',
  'Set as default' => 'Par défaut',
  'Subnet mask' => 'Masque sous-réseau',
  'The current backend cannot be hibernated' => 'Cette source ne peut être mise en veille prolongée.',
  'The current backend cannot be rebooted' => 'Cette source ne peut être redémarrée.',
  'The current backend cannot be shut down' => 'Cette source ne peut être éteinte.',
  'The current backend cannot be suspended' => 'Cette source ne peut être mise en veille.',
  'The current backend is hibernating' => 'Cette source est mise en veille prolongée.',
  'The current backend is not connectable at the moment' => 'La source actuelle n’est pas connectable pour le moment.',
  'The current backend is rebooting' => 'Cette source est en cours de redémarrage.',
  'The current backend is shutting down' => 'Cette source est éteinte.',
  'The current backend is suspending' => 'Cette source est mise en veille.',
  'The following items are only required if you want the backend to me woken using Wake on LAN' => 'Les options suivantes sont utiles uniquement si la source doit être réveillée par la fonction de réveil à distance (Wake-On-Lan).',
  'The server does not ask for authentication' => 'Le serveur ne demande pas d’authentification.',
  'There must be a default backend' => 'Il doit y avoir une source par défaut.',
  'This is where you configure your backends. A 
	backend is an instance of XBMC that the application connects to and serves 
	library contents from. If you specify more than one backend, a new item 
	will appear in the main menu, allowing you to easily switch backends.' => 'Sur cette page il est possible de configurer ses sources. Une source est une instance du logiciel Kodi qui gère le contenu de la vidéothèque. Si plusieurs sources sont configurées, un nouvel objet apparaitra dans le menu permettant de passer d’une source à l’autre.',
  'Unable to connect to {hostname}:{port}, make sure XBMC is running and has its web server enabled' => 'Impossible de se connecter à : {hostname}:{port}, merci de vérifier que le logiciel Kodi est lancé avec son option « Serveur Web activé »',
  'Unable to send WOL packet' => 'Impossibilité d’envoyer un paquet magique (WOL)',
  'Update {backendName}' => 'Mise à jour de : {backendName}',
  'Username' => 'Nom d’utilisateur',
  'Waiting for connection' => 'En attente de connexion',
  'Wake on LAN packet sent, this page will be automatically refreshed once the backend is reachable' => 'Le paquet magique (WOL) a été envoyé, cette page s’actualisera dès lors que la source sera accessible.',
  'You can\'t delete the current backend. Please switch to another one if you want to delete this.' => 'La source actuellement par défaut ne peut être supprimée. Merci de la remplacer par une autre pour supprimer celle par défaut.',
  'You must configure a backend before you can use the application' => 'Une source doit être configurée avant de pouvoir utiliser l’application « XBMC Video Server ».',
);
