<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'This is the system log. You can sort and 
	filter the table freely to find the information you need. To see the full 
	error message (in case it has been clipped), click the view icon on the 
	right. You can also flush the log by pressing the <i>Flush logs</i> 
	button.' => 'Voici l’historique de l’application. Pour y trouver l’information recherchée vous pouvez trier et filtrer l’affichage du tableau situé ci-dessous. Pour lire le message d’erreur complet, cliquez sur l’icône associée et située à droite. Vous pouvez aussi effacer entièrement l’historique en cliquant sur le bouton <i>Effacer l’historique</i>.',
  'Application log' => 'Historique de l’application',
  'Category' => 'Catégorie',
  'Details for log item #{id}' => 'Détails pour l’historique : #{id}',
  'Flush logs' => 'Effacer l’historique',
  'ID' => 'ID',
  'Level' => 'Type',
  'Logtime' => 'Date',
  'Message' => 'Message',
  'Source address' => 'Adresse IP',
  'System log flushed successfully' => 'L’historique a été effacé avec succès',
);
