<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Actions' => 'Actions',
  'Backends' => 'Sources',
  'Browse' => 'Parcourir',
  'Change backend' => 'Modifier la source',
  'Change language' => 'Modifier la langue',
  'Change password' => 'Modifier le mot de passe',
  'Create new' => 'Créer',
  'Flush cache' => 'Supprimer le cache',
  'Interface' => 'Interface',
  'Log out' => 'Se déconnecter',
  'Manage' => 'Gérer',
  'Movies' => 'Films',
  'Power off' => 'Éteindre',
  'Recently added' => 'Derniers ajouts',
  'Settings' => 'Paramètres',
  'System' => 'Application',
  'System log' => 'Historique de l’application',
  'TV shows' => 'Séries TV',
  'Update library' => 'Mettre à jour la vidéothèque',
  'User' => 'Utilisateur',
  'Users' => 'Utilisateurs',
);
