<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to flush the cache?' => 'Confirmer la suppression du cache ?',
  'Are you sure you want to update the backend\'s library?' => 'Confirmer la mise à jour de la vidéothèque ?',
  'Are you sure?' => 'Confirmer cette action ?',
  'Error' => 'Erreur',
  'Error {code}' => 'Erreur {code}',
  'Free your library' => 'Votre vidéothèque partagée',
  'Library update completed' => 'La mise à jour de la vidéothèque est terminée.',
  'Library update has been initiated' => 'La mise à jour de la vidéothèque à été initialisée.',
  'Not available' => 'Non disponible',
  'The cache has been flushed successfully' => 'Le cache a été supprimé avec succès.',
  'You\'ll have to flush the API call cache to see any newly scanned content' => 'Afin de voir les derniers éléments ajoutés à la vidéothèque le cache des résultats de l’API doit être supprimé.',
);
