<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Application subtitle' => 'Sous-titre de l\'application',
  'Access whitelist' => 'Accès par liste blanche',
  'Amount of results to show per page' => 'Nombre de résultats affichés par page',
  'Application language' => 'Langue de l\'application',
  'Application name' => 'Nom de l\'application',
  'Cache all API results' => 'Mettre en cache tous les résultats de l\'API',
  'Changing this will reset the default language for all users' => 'Ce changement aura pour effet d\'assigner la langue par défaut à tous les utilisateurs. Chaque utilisateur pourra à son tour modifier la langue.',
  'Don\'t use playlists when item consists of a single file' => 'Ne pas utiliser de liste de lecture lorsque l\'élément est constitué d\'un seul fichier',
  'Don\'t warn about XBMC version incompatibility' => 'Ne pas avertir à propos des versions d\'XBMC incompatibles',
  'If specified, access is restricted to the defined 
					whitelist. Valid values are IP addresses, IP subnets and 
					domain names (including wildcards). Example: 192.168.1.0/24,1.2.3.4,example.com,*.user.com' => 'L\'accès est restreint par liste blanche. Sont valides : les adresses IP, les IP des sous-réseaux et les noms de domaines incluant les jokers. Exemple: 192.168.1.0/24,1.2.3.4,exemple.fr,*.utilisateur.fr',
  'Ignore article ("the") in results' => 'Ignorer l\'article («le») dans les résultats',
  'Invalid whitelist definition' => 'Saisie de la liste blanche invalide',
  'Leave empty to disable pagination altogether' => 'Laissez vide pour désactiver complètement la pagination',
  'Playlist format' => 'Format du fichier de la liste de lecture',
  'Settings' => 'Paramètres',
  'Settings have been reset to defaults' => 'Les paramètres par défaut ont été rétablis',
  'Settings updated successfully' => 'Les paramètres ont été mis à jour avec succès',
  'Show help blocks throughout the site' => 'Afficher les messages d\'aide sur tout le site',
  'The specified whitelist restrictions will lock you out from this location' => 'Les restrictions spécifiées de la liste blanche vont verrouiller votre accès à l\'application',
  'This is where you configure global 
	application settings. These settings apply regardless of which backend is 
	currently in use.' => 'Voici la configuration générale. Ces paramètres s\'appliquent quelque soit la source utilisée.',
  'Use HTTPS when streaming' => 'Utiliser HTTPS pour le streaming',
  'Useful on slow hardware. A refresh button will appear in the menu which flushes the cache' => 'Utile pour le matériel lent. Un bouton de rafraîchissement apparaît dans le menu permettant de supprimer le cache.',
  'When checked, streaming will be done over HTTPS if 
					the application is accessed over HTTPS. This will usually only 
					work if the server uses a real signed certificate, thus it is 
					not enabled by default.' => 'Le streaming se fera via HTTPS si l\'application est accessible via HTTPS. Cette option est uniquement fonctionnelle si le serveur utilise un certificat signé, ce n\'est donc pas activé par défaut.',
  'You may have to right-click and copy the address in order to stream (not download) the file' => 'Le streaming ne sera fonctionnel que si vous faites un clic droit sur le bouton Voir afin de copier l\'adresse du lien puis l\'ouvrir avec le logiciel VLC.',
);
