<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Watch the whole show' => 'Voir la série entière',
  'Click the name to go to the person\'s IMDb page' => 'Cliquez sur le nom d\'un(e) acteur/trice pour voir la page de sa filmographie sur le site IMDb.',
  'Recently added episodes' => 'Derniers épisodes ajoutés',
  'Season {season} - {showTitle}' => 'Saison {season} - {showTitle}',
  'Seasons' => 'Saison(s)',
  'TV Shows' => 'Séries TV',
  'There are no episodes for this show' => 'Il n\'y a pas d\'épisode pour cette série',
  'Watch the whole season' => 'Voir la saison entière',
  'You can click the show name to jump directly to the show details page' => 'En cliquant sur le nom de la série TV vous accédez à sa page de présentation.',
  'or choose individual episodes from the list below' => 'ou choisissez des épisodes individuellement depuis la liste ci-dessous',
  '{num} episodes' => '{num} épisodes',
);
