<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Start page' => '',
  'This is where you configure users. Every user 
	has a role. Administrators can do anything while a normal user can only 
	switch backends (if more than one has been configured).' => '',
  'This is where you configure users. Every user 
	has a role. Administrators can do anything while a normal user can only 
	switch backends (if more than one has been configured).' => '@@Voici la gestion des utilisateurs. Chaque utilisateur a un rôle. Les administrateurs ont tous les pouvoirs alors que l’utilisateur peut uniquement passer d’une source à l’autre (si plus d’une source a été configuré).@@',
  'Change password' => 'Modifier le mot de passe',
  'Create new user' => 'Créer un nouvel utilisateur',
  'Created user {username}' => 'Utilisateur crée : {username}',
  'Manage users' => 'Gérer les utilisateurs',
  'Password' => 'Mot de passe',
  'Password successfully changed' => 'Mot de passe modifié avec succès',
  'Role' => 'Statut',
  'There must be at least one administrator' => 'Il doit y avoir au moins un administrateur',
  'Update {username}' => 'Mise à jour de l’utilisateur : {username}',
  'Updated user {username}' => 'Utilisateur mis à jour : {username}',
  'Username' => 'Nom d’utilisateur',
);
