<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'If the backend has been powered off completely you\'ll have to turn it on manually.' => '',
  'Backend created successfully' => 'Backend erfolgreich erstellt',
  'Backend name' => 'Backend Name',
  'Backend updated successfully' => 'Backend-Update erfolgreich',
  'Changed backend to {backendName}' => 'Backend-Name geändert: {backendName}',
  'Create new backend' => 'Neues Backend erstellen',
  'Default' => 'Standard',
  'Hostname' => 'Hostname',
  'If a MAC address is entered a Wake-on-LAN packet will be sent to it whenever someone logs in' => 'Nach Eingabe einer MAC-Adresse wird bei jedem Einloggen ein MagigPacket (Wake on LAN) versendet',
  'If you don\'t know what this, leave it empty. Otherwise enter the subnet mask, e.g. 255.255.0.0' => 'Wenn du nicht weißt, was das ist, lass es einfach frei. Andernfalls Subnetzmaske eingeben - beispielsweise: 255.255.0.0.',
  'Invalid MAC address' => 'Ungültige MAC-Adresse',
  'Invalid credentials' => 'Anmeldung fehlgeschlagen',
  'Invalid subnet mask' => 'Ungültige Subnetzmaske',
  'MAC address' => 'MAC Adresse',
  'Manage backends' => 'Backends verwalten',
  'Password' => 'Passwort',
  'Port' => 'Port',
  'Proxy location' => 'Proxy',
  'See {readmeUrl} for how to configure this' => 'Hilfe zur Konfiguration unter : {readmeUrl}',
  'Set as default' => 'Standard setzen',
  'Subnet mask' => 'Subnetzmaske',
  'The current backend is not connectable at the moment' => 'Verbindung zum aktuellen Backend momentan nicht möglich ',
  'The following items are only required if you want the backend to me woken using Wake on LAN' => 'Die folgenden Angaben werden nur für die Wake on LAN Funktion gebraucht.',
  'The server does not ask for authentication' => 'Der Server verlangt keine Authentifizierung',
  'There must be a default backend' => 'Ein Standard Backend muss angegeben werden',
  'This is where you configure your backends. A 
	backend is an instance of XBMC that the application connects to and serves 
	library contents from. If you specify more than one backend, a new item 
	will appear in the main menu, allowing you to easily switch backends.' => 'Hier werden die Backends konfiguriert. Ein Backend ist eine XBMC Instanz die die Medien-Bibliothek zur Verfügung stellt. Bei mehr als einem Backend erscheint ein Hinweis zum Wechseln im Hauptmenü',
  'Unable to connect to {hostname}:{port}, make sure XBMC is running and has its web server enabled' => 'Verbindung zu : {hostname}:{port} fehlgeschlagen, stelle bitte sicher, dass XBMC läuft und der Webserver eingeschaltet ist',
  'Unable to send WOL packet' => ' Wake on LAN fehlgeschlagen',
  'Update {backendName}' => 'Aktualisiere : {backendName}',
  'Username' => 'Benutzername',
  'Waiting for connection' => 'Warte auf Verbindung...',
  'Wake on LAN packet sent, this page will be automatically refreshed once the backend is reachable' => 'MagicPacket (WOL) gesendet, die Seite wird automatisch neugeladen, wenn das Backend erreichbar ist ',
  'You can\'t delete the current backend. Please switch to another one if you want to delete this.' => 'Das aktuelle Backend kann nicht gelöscht werden. Wechsle bitte zu einem anderen, wenn dieses gelöscht werden soll',
  'You must configure a backend before you can use the application' => 'Du musst zuerst ein Backend einrichten, bevor du diese Seite vollständig nutzen kannst',
);
