<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Change language' => '@@Sprache ändern@@',
  'To change the application language for all users go to {settingsUrl} instead' => '@@Um die Spracheinstellung für alle Nutzer zu ändern, gehe zu {settingsUrl}@@',
  'Language changed to {newLanguage}' => 'Sprache geändert: {newLanguage}',
);
