<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'This is the system log. You can sort and 
	filter the table freely to find the information you need. To see the full 
	error message (in case it has been clipped), click the view icon on the 
	right. You can also flush the log by pressing the <i>Flush logs</i> 
	button.' => 'Um Einträge zu finden, kann die Tabelle gefiltert und sortiert werden.',
  'Application log' => 'System Log',
  'Category' => 'Kategorie',
  'Details for log item #{id}' => 'Details zu Nummer: #{id}',
  'Flush logs' => 'Alle Einträge löschen',
  'ID' => 'ID',
  'Level' => 'Typ',
  'Logtime' => 'Datum/Uhrzeit',
  'Message' => 'Bemerkung',
  'Source address' => 'IP Adresse',
  'System log flushed successfully' => 'Alle Einträge gelöscht',
);
