<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Power off' => 'Ausschalten',
    'Actions' => 'Actions',
    'Backends' => 'Backends',
    'Browse' => 'Durchsuchen',
    'Change backend' => 'Backend wechseln',
    'Change language' => 'Sprache ändern',
    'Change password' => 'Passwort ändern',
    'Create new' => 'Neu erstellen',
    'Flush cache' => 'Cache leeren',
    'Interface' => 'Interface',
    'Log out' => 'Abmelden',
    'Manage' => 'Verwalten',
    'Movies' => 'Filme',
    'Recently added' => 'Kürzlich hinzugefügt',
    'Settings' => 'Einstellungen',
    'System' => 'System',
    'System log' => 'System Log',
    'TV shows' => 'TV-Serien',
    'Update library' => 'Bibliothek aktualisieren',
    'User' => 'Benutzer',
    'Users' => 'Benutzer',
);
