<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Free your library' => 'Free your library',
  'Are you sure you want to flush the cache?' => 'Cache wirklich leeren?',
  'Are you sure you want to update the backend\'s library?' => 'Backend wirklich updaten?',
  'Are you sure?' => 'Bist du sicher?',
  'Error' => 'Fehler',
  'Error {code}' => 'Fehler {code}',
  'Library update has been initiated' => 'Bibliothek wird aktualisiert',
  'Not available' => 'Nicht verfügbar',
  'Streaming of video files is not possible from XBMC 12 "Frodo" backends' => 'Streaming funktioniert nicht mit XBMX Version 12 "Frodo"',
  'The cache has been flushed successfully' => 'Der Cache wurde erfolgreich geleert',
  'You\'ll have to flush the API call cache to see any newly scanned content' => 'Um neue Inhalte zu finden, muss der API Cache geleert werden',
);
