<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Director: {director}' => '',
  'Watch' => '',
  'Watch / Download' => 'Stream / Download',
  'Click an image to see other movies with that person, or click the name to go to the person\'s IMDb page' => 'Klicke auf das Foto der/des Schauspielerin/Schauspielers um weitere Filme mit dieser zu finden oder klicke auf den Namen um zur jeweiligen IMDb Seite zu gelangen.',
  'Movies' => 'Filme',
  'Recently added movies' => 'Kürzlich hinzugefügte Filme',
);
