<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Before you get started, please have a look at the application settings' => '',
  'Access whitelist' => 'Zugang - Positivliste',
  'Amount of results to show per page' => 'Anzahl der Ergebnisse pro Seite',
  'Application language' => 'Systemsprache',
  'Application name' => 'Systemname',
  'Application subtitle' => 'Seitenuntertitel',
  'Cache all API results' => 'Cache alle API Ergebnisse',
  'Changing this will reset the default language for all users' => 'Änderungen setzen die Standardsprache für alle Benutzer zurück',
  'Don\'t use playlists when item consists of a single file' => 'Für einzelne Dateien keine Wiedergabeliste benutzen',
  'Don\'t warn about XBMC version incompatibility' => 'Keine Warnung bei inkompatibler XBMC Version ',
  'If specified, access is restricted to the defined 
					whitelist. Valid values are IP addresses, IP subnets and 
					domain names (including wildcards). Example: 192.168.1.0/24,1.2.3.4,example.com,*.user.com' => 'Wenn ausgefüllt, ist der Zugang auf diese Werte beschränkt. Mögliche Eingaben: IP Adressen, IP Subnetze, Domainnamen (auch mit Wildcard). Beispielsweise: 192.168.1.0/24, 1.2.3.4, contoso.com, *.contoso.net',
  'Ignore article ("the") in results' => 'Ignoriere Artikel ("The, der, die, das") in den Ergebnissen',
  'Invalid whitelist definition' => 'Ungültige Einträge der Positivliste',
  'Leave empty to disable pagination altogether' => 'Leer lassen um Seitennummerierung zu deaktivieren',
  'Playlist format' => 'Format der Wiedergabeliste',
  'Settings' => 'Einstellungen',
  'Settings have been reset to defaults' => 'Standardeinstellungen wurden wiederhergestellt ',
  'Settings updated successfully' => 'Einstellungen erfolgreich gespeichert',
  'Show help blocks throughout the site' => 'Hilfe/Tipps innerhalb der Seite anzeigen',
  'The specified whitelist restrictions will lock you out from this location' => 'Die Einschränkungen der Positivliste verhindern jeglichen Zugriff',
  'This is where you configure global 
	application settings. These settings apply regardless of which backend is 
	currently in use.' => 'Allgemeine Systemeinstellungen - Diese gelten unabhängig vom genutzten Backend',
  'Use HTTPS when streaming' => 'Nutze HTTPS zum Streaming',
  'Useful on slow hardware. A refresh button will appear in the menu which flushes the cache' => 'Nützlich bei langsamer Hardware. Eine "Neu laden" Schaltfläche wird erscheinen, welche den Cache leert.',
  'When checked, streaming will be done over HTTPS if 
					the application is accessed over HTTPS. This will usually only 
					work if the server uses a real signed certificate, thus it is 
					not enabled by default.' => 'Nach Aktivierung erfolgt das Streaming per HTTPS, wenn die Seite per HTTPS aufgerufen wird. Funktioniert im Allgemeinen nur mit einem Zertifikat einer Certification Authority (CA). Standardmäßig geaktiviert',
  'You may have to right-click and copy the address in order to stream (not download) the file' => 'Eventuell ist es erforderlich die Adresse zu kopieren und im Player (VLC o.ä.) einzufügen, um die Datei zu streamen und nicht herunterzuladen.',
);
