<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Recently added episodes' => 'Kürzlich hinzugefügte Episoden',
  'Season {season} - {showTitle}' => 'Staffel {season} - {showTitle}',
  'Seasons' => 'Staffeln',
  'TV Shows' => 'TV-Serien',
  'There are no episodes for this show' => 'Diese Serie beinhaltet keine Episoden',
  'Watch the whole season' => 'Ganze Staffel anschauen',
  'Watch the whole show' => 'Ganze Show anschauen',
  'You can click the show name to jump directly to the show details page' => 'Um Details zur Serie zu erhalten, einfach auf den Namen klicken',
  'or choose individual episodes from the list below' => 'oder einzelne Episoden aus der unten stehenden Liste auswählen',
  '{num} episodes' => '{num} Episoden',
);
