<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Change password' => 'Passwort ändern',
  'Create new user' => 'Neuen Benutzer erstellen',
  'Created user {username}' => 'Benutzer erstellt: {username}',
  'Manage users' => 'Benutzer verwalten',
  'Password' => 'Passwort',
  'Password successfully changed' => 'Passwort erfolgreich geändert',
  'Role' => 'Nutzerrolle',
  'Start page' => 'Startseite',
  'There must be at least one administrator' => 'Es muss mindestens einen Administrator geben',
  'This is where you configure users. Every user has a role. Administrators can do anything while a normal user can only switch backends (if more than one has been configured).' => 'Hier werden die Benutzer verwaltet. Jeder Nutzer hat eine Nutzerrolle. Administratoren haben keine Einschränkung, während Benutzer nur die Backends wechseln können (sofern es mehrere gibt).',
  'Update {username}' => 'Update: {username}',
  'Updated user {username}' => 'Benutzer aktualisiert: {username}',
  'Username' => 'Benutzername',
);
